---
title: "SDE12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}


sim_BM <- function(T_, delta) {
  tmesh <- seq(from = 0, to = T_, by = delta)
  N <- length(tmesh)
  step <- delta * T_
  Norm <- rnorm(N)
  B <- c(0, cumsum(sqrt(step) * Norm[-N]))
  output <- data.frame(B = B, Norm = Norm)
  return(output)
}

B_S <- function(mu, sigma, s_0, B, t) {
  s_0 * exp(sigma * B + (mu - (sigma^2 / 2) * t))
}

ex1 <- function(T_, n, mu, sigma, s_0) {
  delta <- T_ / n
  k_n <- floor(6 * n^(0.38))
  BM <- sim_BM(T_ = T_, delta = delta)$B
  delta_vec <- seq(from = 0, to = T_, length.out = n)
  X <- vector(mode = "numeric", length = n)
  sigma_hat <- vector(mode = "numeric", length = n)
  for (i in 1:n) {
    X[i] <- log(B_S(mu = mu, sigma = sigma, s_0 = s_0, B = BM[i], t = delta_vec[i]) / s_0)
  }
  IV <- cumsum(diff(X)^2)
  for (i in 1:n) {
    
    sigma_hat[i] <- (1/(k_n * delta)) * sum(diff(X[i:(i+k_n)])^2)
  }
  output <- list(IV = IV,
                 sigma_hat = sigma_hat)
  return(output)
}

ex1(1, 10000, 0, 1, 1)
```
