---
title: "miniprojekt_2"
output:
  pdf_document:
    extra_dependencies: ["float"]
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(language = "en")
# library(sde)
library(tidyverse)
library(dplyr)
```

# Exercise 1.

## 1.

```{r}

sim_BM <- function(T_, delta) {
  if (delta == 0) {
    return(0)
  } else {
    tmesh <- seq(from = 0, to = T_, by = delta)
  }
  N <- length(tmesh) %>% ceiling()
  Norm <- rnorm(N)
  B <- c(0, cumsum(sqrt(delta) * Norm[-N]))
  return(B)
}

b <- function(x) {
  matrix(c(
    0,
    0.5 - (0.5 + 0) * x[2]
  ), nrow = 2, ncol = 1)
}

sigma <- function(x) {
  matrix(c(
    x[1] * sqrt(1),
    0, 0, 0.4
  ), nrow = 2, ncol = 2) * sqrt(x[2])
}

payoff <- function(x, K) {
  if (is.vector(x)) {
    return(max(x[2] - K, 0))
  } else {
    return(max(x[, 1] - K, 0))
  }
}

algo_1 <- function(M, n, t, T, r, b, sigma, x, payoff, K) {
  if (T - t < 0.0001) {
    return(payoff(x, K))
  } else {
    delta_n <- (T - t) / n
  }
  # print(delta_n)
  last_obs <- matrix(NA, nrow = M, ncol = 2)
  for (j in 1:M) {
    bm1 <- diff(sim_BM(T_ = T, delta = delta_n))
    bm2 <- diff(sim_BM(T_ = T, delta = delta_n))
    bm <- cbind(bm1, bm2)
    X <- matrix(NA, nrow = n + 2, ncol = 2, byrow = TRUE)
    X[1, ] <- x
    for (k in 1:n) {
      # print(delta_n * b(X[k, ]))
      # print(sigma(X[k, ]) %*% bm[k, ])
      # print(n)
      # print(k)
      X[k + 1, ] <- X[k, ] + delta_n * b(X[k, ]) + sigma(X[k, ]) %*% bm[k, ]
    }
    last_obs[j, ] <- X[n + 1, ]
  }
  F <- exp(-r * (T - t)) * 1 / M * sum(payoff(last_obs, K))
  return(F)
}

# algo_1(M = 100, n = 100, t = 0.1, T = 1, r = 0.1, b = b, sigma = sigma, x = c(9, 0.1), payoff = payoff, K = 10)


Heston_euler_payoff <- function(n_, m_, q_, x_min, x_max, v_min, v_max, T, K) {
  delta_n_time <- T / n_
  delta_m_price <- (x_max - x_min) / m_
  delta_q_vol <- (v_max - v_min) / q_
  t <- delta_n_time * 0:n_
  x <- x_min + 0:m_ * delta_m_price
  v <- v_min + delta_q_vol * 0:q_

  result <- matrix(
    data = NA, nrow = (n_ + 1) * (m_ + 1) * (q_ + 1),
    ncol = 4, dimnames = list(c(), c("t", "si", "y", "price"))
  )
  i <- 1
  for (t_ in t) {
    for (si_ in x) {
      for (y_ in v) {
        result[i, c("t", "si", "y", "price")] <- c(
          t_, si_, y_,
          algo_1(
            M = 10, # monte carlo sims
            n = n_ * (T - t_),
            t = t_, T = T, r = 0, b = b, sigma = sigma, x = c(si_, y_), payoff = payoff, K = K
          )
        )
        i <- i + 1
      }
    }
  }
  return(result)
}

```

## 2.

```{r}
ex_2 <- Heston_euler_payoff(
  n_ = 100, m_ = 10, q_ = 10,
  x_min = 0, x_max = 10, v_min = 0,
  v_max = 10, T = 1, K = 1
)
```

## 3.

```{r}

```

## 4.

```{r}

```


## 5.



```{r}

G <- function(tau, x, v) {
  
}



```


## 6.

```{r}

```


## 7.

```{r}


```


## 8.


# Exercise 2.

## 1.2.3

```{r}
X_t <- function(M, n, t, T, r, b, sigma, x) {
  if (T - t < 0.0001) {
    return(payoff(x, K))
  } else {
    delta_n <- (T - t) / n
  }
  Xf <- matrix(NA, nrow=(n+1), ncol=2)
  # print(delta_n)
  last_obs <- matrix(NA, nrow = M, ncol = 2)
  for (j in 1:M) {
    bm1 <- diff(sim_BM(T_ = T, delta = delta_n))
    bm2 <- diff(sim_BM(T_ = T, delta = delta_n))
    bm <- cbind(bm1, bm2)
    X <- matrix(NA, nrow = n + 1, ncol = 2, byrow = TRUE)
    X[1, ] <- x
    for (k in 1:n) {
      # print(delta_n * b(X[k, ]))
      # print(sigma(X[k, ]) %*% bm[k, ])
      # print(n)
      # print(k)
      X[k + 1, ] <- X[k, ] + delta_n * b(X[k, ]) + sigma(X[k, ]) %*% bm[k, ]
    }
  }
  Xf[,1] <- log(X[,1])
  Xf[,2] <- X[,2]
  return(Xf)
}


X_t(M=1, n=10000, t=0, T=1, b=b, sigma=sigma, x=c(1,0.3))
```


## 2.

```{r}
iv <- matrix(NA, nrow=100000, ncol = 4)
theta <- matrix(NA, nrow=100000, ncol = 4)
n <- 10
for(i in 1:4){
  print(i)
  n <- n*10
  X_t_1 <- X_t(M=1, n=n, t=0, T=1, r=0, b=b, sigma=sigma, x=c(1,0.3))
  iv[1:n,i] <- cumsum(diff(X_t_1[,2])^2)
  theta[1:n,i] <- cumsum(diff(X_t_1[,1])^2)
}


```


## 3.

```{r}
iv <- matrix(NA, nrow=100000, ncol = 4)
theta <- matrix(NA, nrow=100000, ncol = 4)
n <- 10
for(i in 1:4){
  n <- n*10
  X_t_1 <- X_t(M=1, n=n, t=0, T=1, r=0, b=b, sigma=sigma, x=c(1,0.3))
  iv[1:n,i] <- cumsum(diff(X_t_1[,2])^2)
  theta[1:n,i] <- cumsum(diff(X_t_1[,1])^2)
}

hat_sigma <- function(k, t, x_t) {
  aa <- 1/(1/n*k)*sum(diff(x_t[t:(t+k)])^2)
  aa
}


hat_sigma_forall_n <- c()
k <- 20
p <- 10000
for (i in 1:p){
  hat_sigma_forall_n[i] <- hat_sigma(k,i, X_t_1[,1])
}

lower_upper_bounds_iv <- sqrt(2/3 * cumsum(diff(X_t_1[,2])^4))

upper_conf_iv <- iv[,4] + 1.96 * lower_upper_bounds_iv
lower_conf_iv <- iv[,4] - 1.96 * lower_upper_bounds_iv
tibble1 <- tibble(upper_conf = upper_conf_iv, lower_conf =lower_conf_iv, implied_vol = iv[,4])

ggplot(data=tibble1,  aes(x=seq(from = 0, to = 1, length.out = nrow(tibble1)))) +
  geom_line(aes(y = upper_conf), color="blue") + 
  geom_line(aes(y=lower_conf), color="blue") + 
  geom_line(aes(y=implied_vol))


lower_upper_bounds_sigma <- sqrt(2/k *hat_sigma_forall_n^2)
upper_conf_sigma <- hat_sigma_forall_n + 1.96 * lower_upper_bounds_sigma
lower_conf_sigma <- hat_sigma_forall_n - 1.96 * lower_upper_bounds_sigma
tibble2 <- tibble(upper_conf = upper_conf_sigma, lower_conf =lower_conf_sigma, sigma_hat = hat_sigma_forall_n)

ggplot(data=tibble2,  aes(x=seq(from = 0, to = 1, length.out = nrow(tibble2)))) +
  geom_line(aes(y = upper_conf), color="blue") + 
  geom_line(aes(y=lower_conf), color="blue") + 
  geom_line(aes(y=sigma_hat))


```
