---
title: "SS_1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(tidyverse)
```



## Exercise 2.

Parameters:

$$  \lambda = x = \bar{\sigma} = T = 1. $$

### 1, 2

By Using a Riemann approximation of $ \int_0^t Z_s ds$, write a code that simulates (with error) the exact solution of $(1)$ (i.e. (2)) on an equally spaced grid of $[0,1]$ given by

$$t_k = \frac{k}{n}, \quad k = 0, \ldots, n, \quad n \in \mathbb{N}.$$


Plot simulated paths for $n = 10000$.


```{r}

set.seed(1)


sim_BM <- function(T_, delta) {
  tmesh <- seq(from = 0, to = T_, by = delta)
  N <- length(tmesh)
  step <- delta * T_
  Norm <- rnorm(N)
  B <- c(0, cumsum(sqrt(step) * Norm[-N]))
  output <- data.frame(B = B, Norm = Norm)
  return(output)
}

Z_t <- function(t, B) {
  exp(0.5 * t + B)
}

b <- function(t, X_t) {
  X_t - X_t^2
}

sigma <- function(t, X_t) {
  X_t
}

sigma_dif <- function(t, X_t) {
  1
}

approx_integral_exact_solution_Euler_sol_Milstein_sol <- function(delta, T_ = 1, b, sigma, x_0 = 0, Z_t, sigma_dif) {
  N_n <- ceiling(T_ / delta)
  tmesh <- seq(from = 0, to = T_, by = delta)
  sim_BM_result <- sim_BM(T_, delta)
  B <- sim_BM_result$B
  X <- c(0)
  X_2 <- c(x_0)
  X_3 <- c(x_0)
  step <- delta * T_
  for (k in 2:(N_n + 1)) {
    # Approximate integral
    X[k] <- X[k - 1] + Z_t(tmesh[k], B[k - 1]) * step
    # Euler scheme
    X_2[k] <- X_2[k - 1] + b(tmesh[k], X_2[k - 1]) * step +
      sigma(tmesh[k], X_2[k - 1]) * (B[k] - B[k - 1])
    # Milstein scheme
    X_3[k] <- X_3[k - 1] + b(tmesh[k], X_3[k - 1]) * step + sigma(tmesh[k], X_3[k - 1]) * (B[k] - B[k - 1]) +
      1 / 2 * sigma(tmesh[k - 1], X_3[k - 1]) * sigma_dif(tmesh[k - 1], X_3[k - 1]) * ((B[k] - B[k - 1])^2 - step)
  }

  XX <- Z_t(t = tmesh, B = B) / (1 + X)
  output <- data.frame(
    exact = XX,
    euler = X_2,
    milstein = X_3
  )
  return(output)
}

plot_sde <- function(n) {
  XX <- approx_integral_exact_solution_Euler_sol_Milstein_sol(
    delta = 1 / n,
    T_ = 1,
    b = b,
    sigma = sigma,
    x_0 = 1,
    Z_t = Z_t,
    sigma_dif = sigma_dif
  )
  par(mfrow = c(3, 1))
  plot.ts(XX$exact)
  plot.ts(XX$euler)
  plot.ts(XX$milstein)
  par(mfrow= c(1,1))
}


plot_sde(10)
plot_sde(100)
plot_sde(1000)
plot_sde(10000)


# Exercise 6.
afstand_max <- function(a, b) {
  dist <- abs(a - b)^2
  max(dist)
}


MC_estimate_comparison <- function(n, MC_n) {
  MC <- data.frame()
  
  for (i in 1:MC_n) {
    output <- approx_integral_exact_solution_Euler_sol_Milstein_sol(
      delta = 1 / n,
      T_ = 1,
      b = b,
      sigma = sigma,
      x_0 = 1,
      Z_t = Z_t,
      sigma_dif = sigma_dif
    )
    MC[i, "Euler"] <- afstand_max(output$exact, output$euler)
    MC[i, "Milstein"] <- afstand_max(output$exact, output$milstein)
  }

  output_data <- data.frame(n = n, Euler_mean_dist = mean(MC$Euler), Milstein_mean_dist = mean(MC$Milstein))
  return(output_data)
}

comp_1 <- MC_estimate_comparison(1, 1000);comp_1
comp_10 <- MC_estimate_comparison(10, 1000);comp_10
comp_50 <- MC_estimate_comparison(50, 1000);comp_50
comp_100 <- MC_estimate_comparison(100, 1000):comp_100

plot_data_mc_est_compa <- bind_rows(comp_1,comp_10,comp_50,comp_100)

ggplot(data = plot_data_mc_est_compa, aes(x = n)) +
  geom_point(aes(y = Euler_mean_dist), color = "red") +
  geom_point(aes(y = Milstein_mean_dist), color = "blue")



```
